package template

const NotEditMark = `
// Code generated by github.com/polpo-studio/gen. DO NOT EDIT.
// Code generated by github.com/polpo-studio/gen. DO NOT EDIT.
// Code generated by github.com/polpo-studio/gen. DO NOT EDIT.
`

const Header = NotEditMark + `
package {{.}}

import(
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/schema"
	"gorm.io/gorm/clause"

	"github.com/polpo-studio/gen"
	"github.com/polpo-studio/gen/field"
	"github.com/polpo-studio/gen/helper"
)
`

const UnitTestHeader = NotEditMark + `
package {{.}}

import(
	"context"
	"fmt"
	"testing"

	"gorm.io/driver/sqlite"
	"gorm.io/gorm"
)
`
